[project]
name = "reef-pi-hass-custom"
version = "0.3.7"
description = "HomeAssistant Reef PI Integration"
authors = [
    {name = "tdragon", email = "1210261+tdragon@users.noreply.github.com"},
]
dependencies = [
    "httpx>=0.27.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.1.1",
    "pytest-homeassistant-custom-component>=0.13.114",
    "pytest-asyncio>=0.23.6",
]
